name: Code Quality

on:
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  trufflehog:
    uses: ./.github/workflows/jobs/truffle-hog.yml

  virus-scan:
    uses: ./.github/workflows/jobs/virus-scan.yml