name: Coding Standards

on:
  pull_request:

jobs:
  stylelint:
    uses: ./.github/workflows/jobs/stylelint.yml

  eslint:
    uses: ./.github/workflows/jobs/eslint.yml

  jest:
    uses: ./.github/workflows/jobs/jest.yml

  phpcs:
    uses: ./.github/workflows/jobs/phpcs.yml

  phpstan:
    uses: ./.github/workflows/jobs/phpstan.yml
