name: Deploy to Develop

on:
  push:
    branches:
    - develop

jobs:
  lint:
    uses: ./.github/workflows/jobs/coding-standards.yml

  test:
    uses: ./.github/workflows/jobs/code-quality.yml

  build:
    uses: ./.github/workflows/jobs/build.yml

  deploy:
    uses: ./.github/workflows/jobs/deploy.yml
    with:
      name: develop
      url: https://develop.fueled.com
