name: JavaScript Coding Standards

on:
  workflow_call:

permissions:
  contents: read

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: "npm"

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Check Node version
        run: node -v

      - name: Setup NPM
        run: npm install -g npm@latest

      - name: Check NPM version
        run: npm -v

      - name: Install dependencies
        run: npm install

      - name: Run Lint JS
        run: npm run lint-js
