name: PHP Checks

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

permissions:
  contents: read

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Validate composer.json and composer.lock
        run: composer run check-deps

      - name: Install dependencies
        run: composer run setup

      - name: Run PHPCS
        run: composer lint

  phpunit:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [ '8.2' ]

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: wordpress_test
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - name: Validate composer.json and composer.lock
        run: composer run check-deps

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Setup WP Tests
        run: bin/install-wp-tests.sh wordpress_test root root 127.0.0.1:${{ job.services.mysql.ports['3306'] }} latest true

      - name: Run PHPUnit on Plugin
        run: composer run test:plugin

      - name: Run PHPUnit on Theme
        run: composer run test:theme
