name: Deploy to Production

on:
  push:
    branches:
    - trunk

jobs:
  lint:
    uses: ./.github/workflows/jobs/coding-standards.yml

  test:
    uses: ./.github/workflows/jobs/code-quality.yml
    needs: lint

  build:
    uses: ./.github/workflows/jobs/build.yml
    needs: test

  deploy:
    uses: ./.github/workflows/jobs/deploy.yml
    needs: build
    with:
      name: production
      url: https://www.fueled.com
