name: Deploy to Production

on:
  push:
    branches:
    - trunk

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    uses: ./.github/workflows/coding-standards.yml

  test:
    uses: ./.github/workflows/code-quality.yml
    needs: lint

  build:
    uses: ./.github/workflows/build.yml
    needs: test

  deploy:
    uses: ./.github/workflows/deploy.yml
    needs: build
    with:
      name: production
      url: https://www.example.com
