name: Deploy to Staging

on:
  push:
    branches:
    - staging

jobs:
  lint:
    uses: ./.github/workflows/coding-standards.yml

  test:
    uses: ./.github/workflows/code-quality.yml
    needs: lint

  build:
    uses: ./.github/workflows/jobs/build.yml
    needs: test

  deploy:
    uses: ./.github/workflows/jobs/deploy.yml
    needs: build
    with:
      name: staging
      url: https://staging.fueled.com
