name: Test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: getong/mariadb-action@v1.1

    - name: Set PHP version
      uses: shivammathur/setup-php@v1
      with:
        php-version: '7.2'
        coverage: none

    - name: Install dependencies
      run: composer install

    - name: Setup WP Tests
      run: bash bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1

    - name: PHPUnit
      run: './vendor/bin/phpunit'
